pipeline:
  agent:
    label: "master"
  stages:
    - stage: "Checkout"
      steps:
        - checkout: {}
    - stage: "Build Docker Image"
      steps:
        - sh "docker build -t <username>/<docker-image-name> ."
    - stage: "Push Docker Image"
      steps:
        - withCredentials([string(credentialsId: 'docker-hub-credentials', variable: 'DOCKER_HUB_CREDENTIALS')]) {
            sh "docker login -u <docker-hub-username> -p ${DOCKER_HUB_CREDENTIALS}"
            sh "docker push <username>/<docker-image-name>"
          }
    - stage: "Deploy to Kubernetes"
      steps:
        - withCredentials([file(credentialsId: 'kubernetes-config', variable: 'KUBECONFIG')]) {
            sh "kubectl apply -f deployment.yml"
            sh "kubectl apply -f service.yml"
          }
